// src/lib/parts/AboutSection.svelte
<script lang="ts">
	import BlobGroupPhoto from '$lib/blobs/BlobGroupPhoto.svelte';
	import Title from '$lib/elements/Title.svelte';
	import Section from '$lib/layout/Section.svelte';
</script>

<Section id="sobre">
	<Title pretitle="Sobre">A Feministech</Title>
	<div class="about">
		<div class="content">
			<p>
				A Feministech é um <b>grupo de pessoas que se identificam no feminino e não bináries</b> que
				produzem, consomem e compartilham conteúdo sobre tecnologia, em um ambiente diverso e inclusivo.
			</p>
			<p>
				O objetivo da Feministech é <b
					>aumentar a representatividade de minorias no mundo da tecnologia</b
				>, que além de serem minorias na tecnologia, também são minorias sociais que precisam de
				mais espaço e alcance em todos os espaços.
			</p>
			<p>
				Uma das principais missões da Feministech é <b
					>auxiliar e incentivar a produção de conteúdo dessas minorias</b
				>, como live coding, vídeos, artigos, palestras, podcasts e eventos.
			</p>
		</div>
		<div class="group-photo">
			<BlobGroupPhoto />
		</div>
	</div>
</Section>

<style lang="scss">
	@import '../scss/vars';

	.about {
		display: flex;
		align-items: center;
		gap: 2rem;

		.content {
			display: flex;
			flex-direction: column;
			gap: 1.5rem;

			b {
				color: $primary;
				font-weight: 400;
			}
		}

		.group-photo {
			width: 30rem;
			flex-shrink: 0;
			margin-right: -3rem;
		}
	}
</style>

// components/AboutSection.vue
<template>
  <section id="sobre" class="about-section">
    <h1>Sobre a Feministech</h1>
    <p>
      A Feministech é um
      <strong>grupo de pessoas que se identificam no feminino e não-bináries</strong>
      que produzem, consomem e compartilham conteúdo sobre tecnologia, em
      um ambiente diverso e inclusivo.
    </p>
    <p>
      O objetivo da Feministech é
      <strong>aumentar a representatividade de minorias no mundo da tecnologia</strong>
      , que além de serem minorias na tecnologia, também são minorias sociais que
      precisam de mais espaço e alcance em todos os espaços.
    </p>

    <p>
      Uma das principais missões da Feministech é
      <strong>auxiliar e incentivar a produção de conteúdo dessas minorias</strong>, como
      <i>live coding</i>, vídeos, artigos, palestras,
      <i>podcasts</i> e eventos.
    </p>
  </section>
</template>

<script>
export default {
  name: 'AboutSection',
}
</script>

<style>
.about-section {
  background-color: whitesmoke;
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: left;
}

.about-section > h1,
strong {
  color: var(--pink);
}
</style>
