// components/Footer.vue
<template>
  <footer>
    <nav class="footerNav">
      <a href="#sobre" class="footerAnchor">Sobre a comunidade</a>
      <a href="#partipantes" class="footerAnchor">Quem participa</a>
      <a href="#projetos" class="footerAnchor">Projetos</a>
      <a href="#eventos" class="footerAnchor">Eventos</a>
      <a href="#contatos" class="footerAnchor">Contatos</a>
    </nav>

    <div class="thanks">
      <span class="thanksTitle"> Feministech </span>

      <span class="thanksText"> Feito com ❤️ </span>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'footerComponent',
}
</script>

<style>
footer {
  background-color: #7109b6;
  height: 25vh;

  display: flex;
  flex-direction: row;
  justify-content: space-around;
  font-family: 'Open Sans', sans-serif;
}

.footerNav {
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  font-weight: 700;
  margin-left: 10vw;
  padding: 1em;
}

.thanks {
  font-family: 'Nunito', sans-serif;
  color: white;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  height: 30%;
  text-align: center;
  margin-right: 10vw;
  margin-top: 8vh;
}

.thanksTitle {
  font-size: 3ch;
  font-weight: 700;
}

.thanksText {
  font-size: 2ch;
}

.footerAnchor {
  text-decoration: none;
  color: white;
  font-size: 2ch;
}
</style>

// src/lib/components/Footer.svelte
<script lang="ts">
	import SocialMediaList from './SocialMediaList.svelte';

	// FIXME: reuse from navbar
	const pages = [
		{ label: 'Início', href: '/' },
		{ label: 'A Feministech', href: '/#sobre' },
		{ label: 'Eventos', href: '/' },
		{ label: 'Projetos', href: '/' },
		{ label: 'Participantes', href: '/' },
		{ label: 'Contato', href: '/' }
	];
</script>

<footer class="footer">
	<nav class="links">
		{#each pages as page}
			<a href={page.href}>{page.label}</a>
		{/each}
	</nav>
	<SocialMediaList />
	<p class="footnote">Feito com <span>💜</span> pela comunidade da Feministech</p>
</footer>

<style lang="scss">
	@import '../scss/vars';

	.footer {
		display: flex;
		flex-direction: column;
		align-items: center;
		width: 100%;
		gap: 2.5rem;
		padding: 4rem 0;
		background-color: #fff;
		border-top: 1px solid rgba(#000, 0.1);
		margin-top: 8rem;
	}

	.links {
		display: flex;
		align-items: center;
		gap: 1.5rem;

		a {
			color: rgba($primary, 0.5);
			text-decoration: none;
			transition: all 0.2s ease;

			&:hover {
				color: $primary;
			}
		}
	}

	.footnote {
		font-size: 12px;
		color: rgba($primary, 0.5);

		span {
			color: $primary;
		}
	}
</style>
